### ISSUE TITLE
Create 12.0 branch

### ISSUE THREAD

**Issue by legalsylvain** [OCA/wallet#8]
Hi all,
I'd like to backport some 14.0 contributions to 12.0. 

@sbidoul, @pedrobaeza, other ? do you know how to initialize the 12.0 branch ? 
Do you I have something to do ? 

thanks.

**Comment by sbidoul** [comment]
You can create the branch, then `pipx run copier copy git+https://github.com/oca/oca-addons-repo-template .` in the repo directory.

**Comment by legalsylvain** [comment]
Thanks a lot for your quick reply @sbidoul.

I made the following : 
```
git clone https://github.com/OCA/wallet && cd wallet
git remote rename origin OCA
git remote add legalsylvain https://github.com/legalsylvain/wallet

git checkout --orphan 12.0
git rm -r --cached . 
rm ./*
pipx run copier copy git+https://github.com/oca/oca-addons-repo-template .
```
the result is here : https://github.com/legalsylvain/wallet/tree/12.0

but I can not ``git push OCA 12.0`` because I'm not the maintainer of the repo.

how can I move forward?

**Comment by sbidoul** [comment]
@legalsylvain I'll push it for you when your branch is green.

**Comment by legalsylvain** [comment]
> @legalsylvain I'll push it for you when your branch is green.

https://github.com/legalsylvain/wallet/tree/12.0 is now green.

thanks !

**Comment by sbidoul** [comment]
An pushed to this repo.
